### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by yhhwpp** [L-movingon/simple-todo-with-react-and#1]
`this.toggle()` 应该是`this.trigger()` 吧？

**Comment by jasonliao** [comment]
@yhhwpp Wow! 你好，你是在哪个文件发现这个问题呢？因为时间隔太久了，没有什么印象了 :joy:

**Comment by yhhwpp** [comment]
@jasonliao simple-todo-with-react-and/reflux/README.md  建议修改下，对象我这样的初学者还是比较有用的

**Comment by jasonliao** [comment]
@yhhwpp 谢谢，已经更正了 :+1:
